### ISSUE TITLE
NOS options should be compiled with app

### ISSUE THREAD

**Issue by jjr840430** [riboseinc/libnereon#16]
`NOS` options should be built as source code format and compiled with the application.

@drystone Do you have any idea to support it?
Here is the [example NOS configuration](https://github.com/riboseinc/libnereon/blob/v0.9.0.7/tests/examples/rvd.nos)

**Comment by drystone** [comment]
@jjr840430, I guess you'll need to expose `struct nereon_nos_options` and/or write a `nos` preprocessor to generate an array of structs from HCL at compile time.

I'd be tempted to support runtime parsing too - something tells me it may be useful. Maybe as a config babel to generate files for 3rd party software so you can for example use HCL to generate Apache configurations.

Or a small tool (`ne`, say) where a user could have a `.config/nereon` directory to store common configurations and something like `ne ls` would launch `ls` with a command line generated by nereon (though I'm not entirely sure why anyone would bother when they might simply create an alias)

**Comment by ronaldtse** [comment]
@drystone so the `*nereon` libraries used to store the NOS (configuration schema definition) as a string and parse them on run-time, but we feel that it would be better, stability and security-wise, to have this parsing performed during compilation and all we leave in the compiled binary are data structures that are immediately useable.

And indeed, generation of other configuration output is a planned work. For example, we could actually represent the entire state of an application (an application group, a system) in NOS (whether this is in UCL/HCL or in another format, e.g. "NJS", "NXS"), and imagine that the input configuration is a dynamic data structure rather than a static file.

As per the last recommendation -- can you help clarify a bit? I couldn't quite understand 😉

**Comment by drystone** [comment]
@ronaldtse I agree entirely. I meant a `.nos` file in the build tree is preprocessed to generate static structs (and man page and validation functions) that can be linked (either visibly or accessible by functions such as "nereon_get_string("option name")`

```
option "proportion" {
    type "float"
    short "p"
    long "proportion"
    /* name is same as key - ie proportion */
    description "Proportion required. Must be between 0.0 and 1.0. You can't have your cake _and_ eat it!"
    assert "f >= 0.0 && f <= 1.0" /* generates  bool nereon_assert_proportion(double f) */
    manual "A much deeper description of the power of proportions"
}
```

It may also be useful to support static definitions of this struct too, so it can be used as an almost drop-in replacement for `getopt`.

The last comment was not a recommendation; more a potential use case for on-the-fly configuration as opposed to static but your suggestions of system-wide configurations are far more appealing :) 

Have you looked at Joey Hess's [Propellor](https://propellor.branchable.com/) - it may be a good source of inspiration.

**Comment by jjr840430** [comment]
@ronaldtse @drystone 

I have implemented the utility to NOS configuration into source and header file.
The source file is [here](https://github.com/riboseinc/libnereon/tree/v0.9.0.7/tools)

Here is the example to use this utility:

```
./tools/nos_to_cc tests/examples/rvd.nos
```

Then it will generate `rvd.nos.c` and `rvd.nos.h` in `tests/examples` directory.
Let me know your opinions.
